### PR TITLE
Feature/revamp home page

### PR DESCRIPTION
**Pull request by andela-skieha**
**What does this PR do?**

Revamps home page

**Description of Task to be completed?**

Implementing a new look for the project's homepage.

**How should this be manually tested?**

Go to the root of the project, run `gulp` then visit `localhost:3000` on your browser.

**What are the relevant pivotal tracker stories?**

[Feature #126978981] (https://www.pivotaltracker.com/n/projects/1454736/stories/126978981)

screen shot 2016-08-31 at 3 55 40 pm

screen shot 2016-08-17 at 10 53 43 am

screen shot 2016-08-17 at 10 53 55 am

### CODE REVIEW

**Comment by gottsohn** [comment]
@andela-skieha We have merge conflicts in this branch.
Also, have you synced with the P.O on this?

**Comment by andela-skieha** [comment]
@gottsohn we had had a discussion about it earlier into the task, but we've asked him about it and are waiting for a response for it.

**Comment by gottsohn** [comment]
@andela-skieha Let's have the merge conflict resolved ASAP Rocky

ASAP Rocky

**Comment by andela-skieha** [comment]
@gottsohn done. 
Haha, ASAP Rocky... nice one

**Comment by gottsohn** [comment]
@andela-skieha yup...you got it.
Anyways, any updates from the PO?

**Comment by andela-skieha** [comment]
@gottsohn not yet. I'm having a call wit him tomorrow, though. I'll have an update by tomorrow afternoon.

**Pull request merged**
